####################################
#+================================+#
#|+==============================+|#
#||                              ||#
#||       TablistPrefixer        ||#
#||             by               ||#
#||       GrimReaper52498        ||#
#||                              ||#
#||   Request by SkilledKevin25  ||#
#|+==============================+|#
#+================================+#
####################################

#THE BELOW TWO OPTIONS ARE IN TESTING AND MAY NOT WORK APPROPRIATELY
#Setting this to true will enable the plugin to get your prefix by
#using your permissions plugin (e.g GroupManager, PEX)
#NOTE: Before setting this to true, ensure rank prefixes
#are 16 characters or less(this includes color codes),
#and also ensure your server is running Vault.

GetPermPrefixes: false

#Set this to true to replace brackets in the prefixes, works with [], <>, () and {}.
ReplaceBrackets: false

#You dont need to change these if the above 'GetPermPrefixes' is true

Owner: '&4Owner '
CoOwner: '&cCoOwner '
HeadAdmin: '&cHeadAdmin '
Admin: '&cAdmin '
HeadMod: '&aHeadMod '
Mod: '&3Mod '
Helper: '&bHelper '
Builder: '&dBuilder '
Developer: '&aDev '

Default: '&7Member '

Donor1: 'Coal '
Donor2: 'Iron '
Donor3: 'Gold '
Donor4: 'Diamond '
Donor5: 'Emerald '
Donor6: 'VIP '
Donor7: 'VIP+ '
Donor8: 'MVP '
Donor9: 'MVP+'
Donor10: 'Sponsor '

#Set this to true to add suffixes to the groups as well
Use-Suffixes: false

Owner-Suffix: '&4Owner '
CoOwner-Suffix: '&cCoOwner '
HeadAdmin-Suffix: '&cHeadAdmin '
Admin-Suffix: '&cAdmin '
HeadMod-Suffix: '&aHeadMod '
Mod-Suffix: '&3Mod '
Helper-Suffix: '&bHelper '
Builder-Suffix: '&dBuilder '
Developer-Suffix: '&aDev '

Default-Suffix: '&7Member '

Donor1-Suffix: 'Coal '
Donor2-Suffix: 'Iron '
Donor3-Suffix: 'Gold '
Donor4-Suffix: 'Diamond '
Donor5-Suffix: 'Emerald '
Donor6-Suffix: 'VIP '
Donor7-Suffix: 'VIP+ '
Donor8-Suffix: 'MVP '
Donor9-Suffix: 'MVP+'
Donor10-Suffix: 'Sponsor '